repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: bd69b816c43306f28bad4d7b303d981b0ecd2fd5
    hooks:
      - id: go-mod-tidy-repo
      - id: go-vet-repo-mod
      - id: go-imports-repo
      - id: go-fmt-repo
      - id: go-build-repo-mod
      - id: go-lint
