name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: CezaryTarnowski-TomTom/gha-inject-secrets-into-file
        with:
          output: .env.test
          secrets: toJson(${{ secrets }})
      - name: Check outputs
        run: |
          grep -q "very secret" .env.test
